site_name: Ad Infinitum
repo_url: https://github.com/Ad-Infinitum-Code/clan-website
edit_uri: ""
theme:
  name: material
  favicon: assets/images/infinity.svg
  icon:
    logo: fontawesome/solid/infinity
    repo: fontawesome/brands/github
  
  # Enable our custom html overrides
  custom_dir: overrides

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"         # user's system preference for light/dark via media query
      scheme: adinf-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"         # user's system preference for light/dark via media query
      scheme: adinf-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  features:
    - navigation.tabs       # top-level sections are rendered in a menu layer below the header for viewports above 1220px, but remain as-is on mobile
    - navigation.instant    # clicks on all internal links will be intercepted and dispatched via XHR without fully reloading the page
    - navigation.tracking   # URL in the address bar is automatically updated with the active anchor as highlighted in the table of contents
    - navigation.top        # A back-to-top button can be shown when the user, after scrolling down, starts to scroll up again
    # - navigation.sections   # top-level sections are rendered as groups in the sidebar for viewports above 1220px, but remain as-is on mobile
    # - navigation.expand     # the left sidebar will expand all collapsible subsections by default, so the user doesn't have to open subsections manually
    # - announce.dismiss      # Allow users to mark announcements as read and dismiss them
    - search.suggest        # search will display the likeliest completion for the last word which can be accepted with the [->] key

# Include our custom css
extra_css:
  - stylesheets/extra.css

extra:
  generator: false          # remove Made with Material for MkDocs notice
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/adinf
      name: Ad Infinitum Discord
    
    - icon: fontawesome/brands/git
      link: https://github.com/Ad-Infinitum-Code
      name: Ad Infinitum Github

# Custom nav layout to ensure raids/dungeons are listed in chronological order
nav:
    - Home: 'index.md'
    - Clan: 'clan/index.md'
    - Dungeons:
        - 'Shattered Throne': 'dungeons/shattered-throne/index.md'
        - 'Pit of Heresy': 'dungeons/pit-of-heresy/index.md'
        - 'Prophecy': 'dungeons/prophecy/index.md'
        - 'Grasp of Avarice': 'dungeons/grasp-of-avarice/index.md'
        - 'Duality': 'dungeons/duality/index.md'
    - Raids:
        - 'Last Wish': 'raids/last-wish/index.md'
        - 'Garden of Salvation': 'raids/garden-of-salvation/index.md'
        - 'Deep Stone Crypt': 'raids/deep-stone-crypt/index.md'
        - 'Vault of Glass': 'raids/vault-of-glass/index.md'
        - 'Vow of the Disciple': 'raids/vow-of-the-disciple/index.md'
        - 'Kings Fall': 'raids/kings-fall/index.md'
    - References: 'references/index.md'

# Enable the use of icons and emojis by using simple shortcodes
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

# Watch additional folders, also triggering a reload for changes made within
watch:
  - overrides
  - extra-yaml

# Plugins and whatnot
plugins:
  - search:
      lang: en
  - glightbox:
      touchNavigation: false
      loop: false
      effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
  - macros:
      include_yaml:
        - extra-yaml/d2-vars.yml
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true
      minify_js: false
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - stylesheets/extra.css
