name: ci 
on:
  push:
    branches:
      - master 
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - 'scripts/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0                          # Recommended for mkdocs-git-revision-date-localized-plugin
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Deploy site
        run: |
          pip install -r requirements.txt
          python3 scripts/weeklies/generate_weekly_rotations.py
          mkdocs gh-deploy --force