name: sync_master_to_actions
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge master
        run: |
          git fetch --unshallow
          git checkout ACTIONS
          git pull
          git merge --no-ff master -m "Sync master to ACTIONS"
          git push
      
      # - name: Push changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     push: origin ACTIONS --set-upstream --force