name: sync_master_to_actions
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          push: origin ACTIONS --set-upstream --force