name: weekly_reset
on:
  schedule:
    # - cron: 0 17 * * 2 # Every tuesday at 1700 UTC (weekly reset)
    - cron: '*/5 * * * *' # TESTING: every 2 minutes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Run the script
        run: |
          pip install -r requirements.txt
          python3 scripts/generate_weekly_rotations.py

      - name: Add generated weeklies.yml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'extra-yaml/weeklies.yml'
          author_name: 'Weekly Reset Bot'
          author_email: 'WeeklyResetBot@AdInfinitumClan.com'
